### ISSUE TITLE
Cannot Remove Tags with 'x'

### ISSUE THREAD

**Issue by Mjvolk3** [microsoft/vscode-jupyter-cell-tags#3]
When 'first' tag is added to a cell clicking the 'x' does not remove the tag.

![image](https://user-images.githubusercontent.com/48566106/191656093-52734601-6e9a-4076-b54e-c760c15f2cbd.png)

I get the following VsCode error.

![image](https://user-images.githubusercontent.com/48566106/191656183-0b2502a0-b4e5-4164-8307-d5c3fdfcf78c.png)

VsCode Version: 1.71
OS: macOS Monterey Version 12.6

**Comment by AndrewBasem1** [comment]
Same error here, the `+Tag` button is not working as well.

Gives the following error message:
![image](https://user-images.githubusercontent.com/102801029/191786750-f4b27905-77c1-461c-920b-5d2c744fbb4b.png)

**Comment by rebornix** [comment]
Thanks I think it's probably that we didn't activate the extension on command execution. Will push a fix soon.

**Comment by rebornix** [comment]
0.1.2 is published now. Please give it a try and let me know if you are still seeing the issue. If that happens, let's see how we can get more info from you to have it resolved. Thanks in advance!

**Comment by AndrewBasem1** [comment]
@rebornix It's still giving the same error, checked with 0.1.2 and 0.1.3 both have this issue.

**Comment by The-Compiler** [comment]
I can confirm with 0.1.3 - all I get is "actual command NOT FOUND", with no functionality (other than viewing tags) seemingly working.

The "Log (Extension Host)" output window shows:

```
[2022-09-27 17:15:29.967] [exthost] [error] actual command NOT FOUND _vscode_delegate_cmd_l8kcb9rm undefined
```
